config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }

  devise_scope :user do
    authenticated :user do
      root 'transactions#index', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  resources :transactions, only: :index
  resources :transfers, only: %i[new create]
end

app/models/account.rb
# frozen_string_literal: true

class Account < ApplicationRecord
  has_paper_trail

  belongs_to :user
  has_many :transactions, lambda { |acc|
                            unscope(:where).where(from_account: acc).or(where(to_account: acc))
                          }

  validates :user_id, uniqueness: { case_sensitive: false }
  validates :account_number, presence: true, uniqueness: { case_sensitive: false }
  validates :balance_in_cents, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  before_validation :generate_account_number, on: :create

  def balance
    BigDecimal((balance_in_cents / 100.00).to_s)
  end

  private

  def generate_account_number
    return if persisted?

    loop do
      self.account_number = rand.to_s[2..9]

      break unless Account.where(account_number:).exists?
    end
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/transaction.rb
# frozen_string_literal: true

class Transaction < ApplicationRecord
  enum transaction_type: { deposit: 'deposit', transfer: 'transfer' }

  belongs_to :from_account, class_name: 'Account', optional: true
  belongs_to :to_account, class_name: 'Account'

  validates :amount_in_cents, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :from_account_id, presence: true, if: -> { transfer? }

  def amount
    BigDecimal((amount_in_cents / 100.00).to_s)
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable

  has_one :account

  validates :name, presence: true
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :set_paper_trail_whodunnit
  before_action :configure_permitted_parameters, if: :devise_controller?

  helper_method :current_account

  def current_account
    @current_account ||= current_user.account
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/registrations_controller.rb
# frozen_string_literal: true

class RegistrationsController < Devise::RegistrationsController
  after_action :create_account, only: :create

  protected

  def create_account
    resource.build_account.save! if resource.persisted? # user is created successfuly
  end
end

app/controllers/transactions_controller.rb
# frozen_string_literal: true

class TransactionsController < ApplicationController
  before_action :authenticate_user!

  def index
    @transactions = current_account.transactions.includes(:from_account, :to_account)
  end
end

app/controllers/transfers_controller.rb
# frozen_string_literal: true

class TransfersController < ApplicationController
  before_action :authenticate_user!

  def new; end

  def create
    @service = TransferService.new(from_account: current_account,
                                   to_account_number: params[:to_account_number],
                                   amount: params[:amount])

    if @service.valid?
      @service.save
      redirect_to transactions_path, notice: 'Transfer successfully created!'
    else
      render :new
    end
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BankingApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/skeleton/2.0.4/skeleton.min.css" integrity="sha512-EZLkOqwILORob+p0BXZc+Vm3RgJBOe1Iq/0fiI7r/wJgzOFZMlsqTa29UEl6v6U6gsV4uIpsNZoV32YZqrCRCQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
  </head>

  <body>
    <p class="notice" style="color: #3dad4a"><%= notice %></p>
    <p class="alert" style="color: #e62e2e"><%= alert %></p>
    <% if current_user && current_account %>
      <h2>Hi <%= current_user.name %>!</h2>
      <p>Your balance is $ <%= sprintf('%0.02f', current_account.balance) %>.</p>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/transactions/index.html.erb
<p>
  Your account number is <b><%= current_account.account_number %></b>.
  Share it with your friends so they can send you money!
</p>

<%= button_to 'Transfer money', new_transfer_path, method: :get, class: 'button-primary' %>

<% if @transactions.any? %>
  <h3>Transactions</h3>

  <table>
    <thead>
      <tr>
        <th>Date</th>
        <th>Description</th>
        <th>Amount</th>
      </tr>
    </thead>
    <tbody>
      <% @transactions.each do |transaction| %>
        <tr>
          <td><%= I18n.l(transaction.created_at, format: :long) %></td>
          <td>
            <% if transaction.deposit? %>
              Deposit
            <% else %>
              Transfer
              <% if transaction.to_account == current_account %>
                from account number <%= transaction.from_account.account_number %>
              <% else %>
                to account number <%= transaction.to_account.account_number %>
              <% end %>
            <% end %>
          </td>
          <td>$ <%= sprintf('%0.02f', transaction.amount) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

<br>

<%= button_to 'Logout', destroy_user_session_path, method: :delete %>

app/views/transfers/new.html.erb
<h1>New transfer</h1>

<% if @service && @service.errors.any? %>
  <% @service.errors.full_messages.each do |error_msg| %>
    <p style="color: #e62e2e"><%= error_msg %></p>
  <% end %>
<% end %>

<%= form_with url: '/transfers', method: :post, data: { turbo: false } do |form| %>
  <%= form.label :to_account_number %>
  <%= form.number_field :to_account_number, required: true %>
  <br>
  <%= form.label :amount, 'Amount $' %>
  <%= form.number_field :amount, min: 0.01, step: 0.01, required: true %>
  <br>
  <%= form.submit 'Transfer', class: 'button-primary' %>
<% end %>

<%= button_to 'Back', transactions_path, method: :get %>